# -*- coding: utf-8 -*-
"""Ai based resume screening even non ATS resume

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_76WrBzXh2f_7bEUkhf3iFyEz9ryTU08
"""

!apt-get install -y tesseract-ocr
!pip install -q pytesseract pillow sentence-transformers docx2txt pandas scikit-learn tqdm gradio

import pytesseract
from PIL import Image
import docx2txt
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import gradio as gr
import os

model = SentenceTransformer("all-MiniLM-L6-v2")

def extract_resume_text(file_path):
    try:
        if file_path.endswith(".docx"):
            return docx2txt.process(file_path)

        elif file_path.endswith(".txt"):
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                return f.read()

        elif file_path.lower().endswith((".png", ".jpg", ".jpeg")):
            image = Image.open(file_path)
            return pytesseract.image_to_string(image)

        else:
            return ""
    except:
        return ""

MATCH_THRESHOLD = 80
MIN_TEXT_LENGTH = 30

def process_resumes(files, job_description):
    results = []

    job_embedding = model.encode(job_description)

    for file in files:
        text = extract_resume_text(file.name).lower().strip()

        if len(text) < MIN_TEXT_LENGTH:
            results.append({
                "Resume Name": os.path.basename(file.name),
                "Match Percentage": 0.0
            })
            continue

        resume_embedding = model.encode(text)
        score = cosine_similarity(
            [resume_embedding], [job_embedding]
        )[0][0]

        results.append({
            "Resume Name": os.path.basename(file.name),
            "Match Percentage": round(score * 100, 2)
        })

    df = pd.DataFrame(results).sort_values(
        by="Match Percentage", ascending=False
    )

    summary = (
        f"Total resumes processed : {len(df)}\n"
        f"Resumes Selected (≥80%) : {len(df[df['Match Percentage'] >= MATCH_THRESHOLD])}\n"
        f"Resumes Rejected (<80%) : {len(df[df['Match Percentage'] < MATCH_THRESHOLD])}"
    )

interface = gr.Interface(
    fn=process_resumes,
    inputs=[
        gr.File(
            file_types=[".png", ".jpg", ".jpeg", ".docx", ".txt"],
            file_count="multiple",
            label="Upload Resumes"
        ),
        gr.Textbox(
            lines=4,
            placeholder="Enter Job Description here...",
            label="Job Description"
        )
    ],
    outputs=[
        gr.Dataframe(
            label="Resume Match Results",
            interactive=False
        ),
        gr.Textbox(
            label="Summary"
        )
    ],
    title="AI Resume Screening System",
    description=(
        "OCR + Semantic AI based resume matcher. "
        "Supports scanned resumes, DOCX, and TXT files."
    )
)

interface.launch(debug=True)